name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: deps
      run: bash ${GITHUB_WORKSPACE}/setup_deps.sh
    - name: make
      run: make
    - name: print help
      run: ./ddfb
    - name: Upload linux amd64 binary
      uses: actions/upload-artifact@v2
      with:
        name: ddfb-amd64
        path: ddfb
  build-win:
    name: Build with MSVC
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Compile dependencies
      run: bash ${GITHUB_WORKSPACE}/setup_deps.sh
      shell: bash
    - name: Compile ddfb
      run: |
        cmake .
        cmake --build . --config MinSizeRel
    - name: Print help
      run: .\MinSizeRel\ddfb.exe
      shell: cmd
    - name: Upload win64 binary
      uses: actions/upload-artifact@v2
      with:
        name: ddfb-win64
        path: .\MinSizeRel\ddfb.exe
