name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: deps
      run: ./setup-deps.sh
    - name: make
      run: make
    - name: print help
      run: ./ddfb
